language: android

android:
  components:
    - tools
    - platform-tools
    - build-tools-25.0.2
    - extra-android-m2repository
    - extra-android-support
    - android-25

jdk:
  - oraclejdk8

script:
  - gradle clean build


notifications:
  email: false

sudo: required

cache:
  directories:
    - $HOME/.gradle
